<?php

// State
$config['states'] = ["Choose States","Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli","Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"];

// Districts
$config['state'] = ["Choose District"];
$config['state1'] = ["Choose District","Nicobar","North and Middle Andaman","South Andaman"];
$config['state2'] = ["Choose District","Anantapur","Chittoor","East Godavari","Guntur","Krishna","Kurnool","Nellore","Prakasam","Srikakulam","Visakhapatnam","Vizianagaram","West Godavari","YSR Kadapa","Rajampet","Pulivendula"];
$config['state3'] = ["Choose District","Changlang ","Tirap ","Anjaw ","Lohit ","Upper Dibang Valley","Lower Dibang Valley","West Siang ","East Siang ","Lower Subansiri ","Upper Siang ","Kurung Kumey ","Upper Subansiri ","East Kameng ","Papum Pare ","Tawang ","West Kameng "];
$config['state4'] = ["Choose District","Baksa","Barpeta","Biswanath","Bongaigaon","Cachar","Charaideo","Chirang","Darrang","Dhemaji","Dhubri","Dibrugarh","Goalpara","Golaghat","Hailakandi","Hojai","Jorhat","Kamrup Metropolitan","Kamrup","Karbi Anglong","Karimganj","Kokrajhar","Lakhimpur","Majuli","Morigaon","Nagaon","Nalbari","Sivasagar","Sonitpur","South Salmara-Mankachar","Tinsukia","Udalguri","West Karbi Anglong"];
$config['state5'] = ["Choose District","West Champaran","Vaishali","Supaul","Siwan","Sitamarhi","Sheohar","Sheikhpura","Saran","Samastipur","Saharsa","Rohtas","Purnia","Patna","Nawada","Nalanda","Muzaffarpur","Munger","Madhubani","Madhepura","Lakhisarai","Kishanganj","Khagaria","Katihar","Kaimur","Jehanabad","Jamui","Gopalganj","Gaya","East Champaran","Darbhanga","Buxar","Bhojpur","Bhagalpur","Begusarai","Banka","Aurangabad","Arwal","Araria"];
$config['state6'] = ["Choose District","Balod","Baloda Bazar","Balrampur","Bemetara","Bijapur","Bilaspur","Dantewada","Dhamtari","Durg","Gariaband","Jagdalpur (Madhya Bastar)","Janjgir-Champa","Jashpur","Kabirdham","Kanker","Kondagaon","Korba","Koriya","Mahasamund","Mungeli","Narayanpur","Raigarh","Raipur","Rajnandgaon","Sukma","Surajpur","Surguja"];
$config['state7'] = ["Choose District","Balod","Baloda Bazar","Balrampur","Bemetara","Bijapur","Bilaspur","Dantewada","Dhamtari","Durg","Gariaband","Jagdalpur (Madhya Bastar)","Janjgir-Champa","Jashpur","Kabirdham","Kanker","Kondagaon","Korba","Koriya","Mahasamund","Mungeli","Narayanpur","Raigarh","Raipur","Rajnandgaon","Sukma","Surajpur","Surguja"];
$config['state8'] = ["Choose District","Dadra and Nagar Haveli"];
$config['state9'] = ["Choose District","Daman","Diu"];
$config['state10'] = ["Choose District","New Delhi","North Delhi","North West Delhi","West Delhi","South West Delhi","South Delhi","South East Delhi","Central Delhi","North East Delhi","Shahdara","East Delhi"];
$config['state11'] = ["Choose District","North Goa","South Goa"];
$config['state12'] = ["Choose District","Ahmedabad","Amreli","Anand","Aravalli","Banaskantha","Bharuch","Bhavnagar","Botad","Chhota Udaipur","Dahod","Dang","Devbhoomi Dwarka","Gandhinagar","Gir Somnath","Jamnagar","Junagadh","Kutch","Kheda","Mahisagar","Mehsana","Morbi","Narmada","Navsari","Panchmahal","Patan","Porbandar","Rajkot","Sabarkantha","Surat","Surendranagar","Tapi","Vadodara","Valsad"];
$config['state13'] = ["Choose District","Ambala","Bhiwani","Charkhi Dadri","Faridabad","Fatehabad","Gurgaon","Hisar","Jhajjar","Jind","Kaithal","Karnal","Kurukshetra","Mahendragarh","Nuh","Palwal","Panchkula","Panipat","Rewari","Rohtak","Sirsa","Sonipat","Yamunanagar"];
$config['state14'] = ["Choose District","Bilaspur","Chamba","Hamirpur","Kangra","Kinnaur","Kullu","Lahaul and Spiti","Mandi","Shimla","Sirmaur","Solan","Una"];
$config['state15'] = ["Choose District","Doda","Jammu","Kathua","Kishtwar","Poonch","Rajouri","Ramban","Reasi","Samba","Udhampur","Anantnag","Bandipora","Baramulla","Budgam","Ganderbal","Kulgam","Kupwara","Pulwama","Shopian","Srinagar"];
$config['state16'] = ["Choose District","Garhwa","Palamu","Latehar","Chatra","Hazaribagh","Koderma","Giridih","Ramgarh","Bokaro","Dhanbad district","Lohardaga","Gumla","Simdega","Ranchi","Khunti","West Singhbhum","Saraikela Kharsawan","East Singhbhum","Jamtara","Deoghar","Dumka","Pakur","Godda","Sahebganj"];
$config['state17'] = ["Choose District","Bagalkot","Belagavi","Vijayapura","Dharwad","Gadag","Haveri","Uttara Kannada","Bengaluru Urban","Bengaluru Rural","Chikkaballapur","Chitradurga","Davanagere","Kolar","Ramanagara","Shivamogga","Tumakuru","Ballari","Bidar","Kalaburagi","Koppal","Raichur","Yadgir","Chamarajanagar","Chikkamagaluru","Dakshina Kannada","Hassan","Kodagu","Mandya","Mysuru","Udupi"];
$config['state18'] = ["Choose District","Alappuzha","Ernakulam","Idukki","Kannur","Kasaragod","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
$config['state19'] = ["Choose District","Lakshadweep"];
$config['state20'] = ["Choose District","Bhopal","Raisen","Rajgarh","Sehore","Vidisha","Morena","Sheopur","Bhind","Gwalior","Ashoknagar","Shivpuri","Datia","Guna","Alirajpur","Barwani","Burhanpur","Indore","Dhar","Jhabua","Khandwa","Khargone","Balaghat","Chhindwara","Jabalpur","Katni","Mandla","Narsinghpur","seoni","Betul","Harda","Hoshangabad","Rewa","Satna","Sidhi","Singrauli","Chhatarpur","Damoh","Panna","Sagar","Tikamgarh","Anuppur","Shahdol","Umaria","Agar Malwa","Dewas","Mandsaur","Neemuch","Ratlam","Shajapur","Ujjain"];
$config['state21'] = ["Choose District","Akola","Amravati","Buldana","Yavatmal","Washim","Aurangabad","Beed","Jalna","Osmanabad","Latur","Nanded","Parbhani","Hingoli","Mumbai City","Mumbai Suburban","Thane","Palghar","Raigad","Ratnagiri","Sindhudurg","Bhandara","Chandrapur","Gadchiroli","Gondia","Nagpur","Wardha","Ahmednagar","Dhule","Jalgaon","Nandurbar","Nashik","Kolhapur","Pune","Sangli","Satara","Solapur"];
$config['state22'] = ["Choose District","Bishnupur","Thoubal","Imphal East","Imphal West","Senapati","Ukhrul","Chandel","Churachandpur","Tamenglong","Jiribam","Kangpokpi (Sadar Hills)","Kakching","Tengnoupal","Kamjong","Noney","Pherzawl"];
$config['state23'] = ["Choose District","West Jaintia","East Jaintia","East Khasi","West Khasi","South West Khasi","Ri-Bhoi (Nongpoh)","North Garo","East Garo","South Garo","West Garo","South West Garo"];
$config['state24'] = ["Choose District","Aizawl","Kolasib","Lawngtlai","Lunglei","Mamit","Siaha","Serchhip","Champhai"];
$config['state25'] = ["Choose District","Dimapur","Kiphire","Kohima","Longleng","Mokokchung","Mon","Peren","Phek","Tuensang","Wokha","Zunheboto"];
$config['state26'] = ["Choose District","Angul","Boudh (Baudh)","Balangir","Bargarh (Baragarh)","Balasore (Baleswar)","Bhadrak","Cuttack","Debagarh (Deogarh)","Dhenkanal","Ganjam","Gajapati","Jharsuguda","Jajpur","Jagatsinghapur","Khordha","Kendujhar (Keonjhar)","Kalahandi","Kandhamal","Koraput","Kendrapara","Malkangiri","Mayurbhanj","Nabarangpur","Nuapada","Nayagarh","Puri","Rayagada","Sambalpur","Subarnapur (Sonepur)","Sundergarh"];
$config['state27'] = ["Choose District","Karaikal","Mahe","Pondicherry","Yanam"];
$config['state28'] = ["Choose District ","Amritsar", "Bathinda", "Faridkot", "Firozpur", "Fatehgarh Sahib", "Kapurthala", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Ludhiana", "Mansa", "Moga", "Muktsar", "Nawanshahr"," Patiala"," Rupnagar"," Sangrur","Tarn Taran"];
$config['state29'] = ["Choose District","Ajmer","Alwar","Banswara","Baran","Barmer","Bharatpur","Bhilwara","Bikaner","Bundi","Chittorgarh","Churu","Dausa","Dholpur","Dungarpur","Hanumangarh","Jaipur","Jaisalmer","Jalor","Jhalawar","Jhunjhunu","Jodhpur","Karauli","Kota","Nagaur","Pali","Pratapgarh","Rajsamand","Sawai Madhopur","Sikar","Sirohi","Sri Ganganagar","Tonk","Udaipur"];
$config['state30'] = ["Choose District","East Sikkim","North Sikkim","South Sikkim","West Sikkim"];
$config['state31'] = ["Choose District","Ariyalur","Karur","Nagapattinam","Perambalur","Pudukkottai","Thanjavur","Tiruchirappalli","Tiruvarur"];
$config['state32'] = ["Choose District","Adilabad","Bhadradri Kothagudem","Hyderabad","Jagtial","Jangaon","Jayashankar Bhupalapally","Jogulamba Gadwal","Kamareddy","Karimnagar","Khammam","Kumarambheem Asifabad","Mahabubabad","Mahabubnaar","Mancheria","Medak","Medchal–Malkajgiri","Nagarkurnoo","Nalgonda","Nirmal","Nizamabad","Peddapalli","Rajanna Sirclla","Ranga Redd","Sangareddy","Siddipe","Suryapet","Vikarabad","Wanaparthy","Warangal Rural","Warangal Urban","Yadadri Bhuvanagiri"];
$config['state33'] = ["Choose District","Dhalai","South Tripura","Gomati","North Tripura","Sipahijala","Khowai","West Tripura","Unakoti"];
$config['state34'] = ["Choose District","Allahabad","Moradabad","Ghaziabad","Azamgarh","Lucknow","Kanpur Nagar","Jaunpur","Sitapur","Bareilly","Gorakhpur","Agra","Muzaffarnagar","Hardoi","Kheri","Sultanpur","Bijnor","Budaun","Varanasi","Aligarh","Ghazipur","Kushinagar","Bulandshahar","Bahraich","Saharanpur","Meerut","Gonda","Rae Bareli","Barabanki","Ballia","Pratapgarh","Unnao","Deoria","Shahjahanpur","Maharajganj","Fatehpur","Siddharth Nagar","Mathura","Firozabad","Mirzapur","Faizabad","Basti","Ambedkar Nagar","Rampur","Mau","Balrampur","Pilibhit","Jhansi","Chandauli","Farrukhabad","Mainpuri","Sonbhadra","Jyotiba Phule Nagar","Banda","Ramabai Nagar","Etah","Sant Kabir Nagar","Jalaun","Kannauj","Gautam Buddha Nagar","Kaushambi","Etawah","Sant Ravidas Nagar","Mahamaya Nagar","Kanshiram Nagar","Auraiya","Baghpat","Lalitpur","Shrawasti","Hamirpur","Chitrakoot","Mahoba"];
$config['state35'] = ["Choose District","Dehradun","Haridwar","Tehri Garhwal","Uttarkashi","Chamoli","Pauri Garhwal","Rudraprayag"];
$config['state36'] = ["Choose District","North 24 Parganas","South 24 Parganas","Bardhaman","Murshidabad","West Midnapore","Hooghly","Nadia","East Midnapore","Howrah","Kolkata","Malda","Jalpaiguri","Bankura","Birbhum","North Dinajpur","Purulia","Cooch Behar","Darjeeling","South Dinajpur"];